name: Reusable workflow example

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string

jobs:
  getEnvs:
    name: Get variables from repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Read yaml
        uses: mikefarah/yq@v4.26.1
      - id: yq
        run: yq '.lang' $GITHUB_WORKSPACE/variables.yml 
      - name: Display read-yaml output
        run: echo "${{ steps.yq.outputs }}"  

  job1:
    name: job1
    needs: [getEnvs]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1 - step1"
      - run: echo "job1 - step2"
  job2:
    name: job2
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2 - step1"
      - run: echo "job2 - step2"
  job3:
    name: job3
    needs: [job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job3 - step1"
      - run: echo "job3 - step2"
  job4:
    name: job4
    needs: [job3]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job4 - step1"
      - run: echo "job4 - step2"
