name: Reusable workflow example

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string

jobs:
  getEnvs:
    name: Get variables from repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Read yaml
        uses: mikefarah/yq@v4.26.1
      - id: vars
        run: echo ::set-output name=lang::$(yq '.lang' $GITHUB_WORKSPACE/variables.yml)
      - uses: nick-fields/persist-action-data@v1
        with:
          data: ${{ steps.vars.outputs.lang }}
          variable: LANG
      
  job1:
    name: job1
    needs: [getEnvs]
    runs-on: ubuntu-latest
    steps:
      - uses: nick-fields/persist-action-data@v1
        with:
          retrieve_variables: LANG

  job2:
    name: job2
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - uses: nick-fields/persist-action-data@v1
        with:
          retrieve_variables: LANG
      - run: echo "job2 - nodejs"
        if: env.LANG == 'nodejs' 
      - run: echo "job2 - java"
        if: env.LANG == 'java' 
      - run: echo "job2 - go"
        if: env.LANG == 'go'

  job3:
    name: job3
    needs: [job2]
    runs-on: ubuntu-latest
    steps:
      - uses: nick-fields/persist-action-data@v1
        with:
          retrieve_variables: LANG
      - run: echo "job3 - nodejs"
        if: env.LANG == 'nodejs' 
      - run: echo "job3 - java"
        if: env.LANG == 'java' 
      - run: echo "job3 - go"
        if: env.LANG == 'go'
